# NumPy
**Array**:<br>
Estructura ordenada e indexada y accesible independeientemetne.  Es el principal elemento de *NumPy* y esta librería está optimizada para acceder a los datos de manera mas eficiente que las listas de python.

para importar librería

In [1]:
import numpy as np

Defino lista y lo incorporo a numpy.  Es un elemento de una dimensión

In [3]:
ls=[1,2,3,4,5,6,7,8,9]
arr=np.array(ls)
ls2=np.arange(1,10)
print("ls2",ls2)
print(type(ls))
print(ls)
print(type(arr))
print(arr)

ls2 [1 2 3 4 5 6 7 8 9]
<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


Para definir un objeto de varias dimensiones se utilizan varios elementos de una dimensión, por ejemplo para generar un elemento de 2 dimensiones:

In [4]:
mtp = [["juan",1,2,3,True],["Maria",4,5,6,False],["jose",7,8,9,False]]
mt=np.array(mtp)
print(type(mtp))
print(mtp)
print(type(mt))
print(mt)

<class 'list'>
[['juan', 1, 2, 3, True], ['Maria', 4, 5, 6, False], ['jose', 7, 8, 9, False]]
<class 'numpy.ndarray'>
[['juan' '1' '2' '3' 'True']
 ['Maria' '4' '5' '6' 'False']
 ['jose' '7' '8' '9' 'False']]


Se accede a los elementos de la misma manera que python accede a las listas, de esta manera se pueden utilizar los elementos para distintos fines, por ejemplo:

In [5]:
print(arr[3])
print(arr[6])
print(arr[3]+arr[6])

4
7
11


Para acceder a los elemento de una matriz se puede acceder primero al numero de fila, y luego al numero de columna, y tambien pueden usarse para cualquier operación.<br>
También puede accederse separando dentro del corchete de la matriz ubicando en el mismo orden (fila, columa) separando los valores con coma ",".

In [6]:
print(mt[1][3])
print(mt[0][2])
print(int(mt[1,3])-int(mt[0,2]))

6
2
4


Del mismo modo se accede a rango de valores con slicing.

In [7]:
print(arr[2:6])
print(mt[:2,1:3])

[3 4 5 6]
[['1' '2']
 ['4' '5']]


**Generar un array de 3 dimensiones de 3 por 3 con los multiplos del 1 al 9 para las dimensiones 2, 3 y 4.**

In [16]:
ran=range(1,10)
m0=[]
m1=[]
m2=[]
for dim in (2, 3, 4):
    for x in ran:
        val=dim*(int(x))
        m0.append(val)
    #print("vector",m0)
    m1.append(m0[:3])
    #print("m ",dim," - 1", m1)
    m1.append(m0[3:6])
    #print("m ",dim," - 2", m1)
    m1.append(m0[6:])
    #print("m ",dim," - 3", m1)
    m0=[]
    m2.append(m1)
    #print("matriz",m1)
    m1=[]
print("cubo",m2)


cubo [[[2, 4, 6], [8, 10, 12], [14, 16, 18]], [[3, 6, 9], [12, 15, 18], [21, 24, 27]], [[4, 8, 12], [16, 20, 24], [28, 32, 36]]]


Buscar el numero 15, 16 y 28 con la lista (m2) y con *NumPy*

In [18]:
print("="*50)
print("Busqueda por la lista")
print(m2)
print("-"*50)
print(m2[1][1][1])
print(m2[0][2][1])
print(m2[2][2][0])
print("="*50)
print("Busqueda por NumPy")
print("-"*50)
m3d=np.array(m2)
print(m3d)
print(m3d[1,1,1])
print(m3d[0,2,1])
print(m3d[2][2][0])

Busqueda por la lista
[[[2, 4, 6], [8, 10, 12], [14, 16, 18]], [[3, 6, 9], [12, 15, 18], [21, 24, 27]], [[4, 8, 12], [16, 20, 24], [28, 32, 36]]]
--------------------------------------------------
15
16
28
Busqueda por NumPy
--------------------------------------------------
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 3  6  9]
  [12 15 18]
  [21 24 27]]

 [[ 4  8 12]
  [16 20 24]
  [28 32 36]]]
15
16
28


### Tipos de datos
dtype, devuelve el tipo de dato que se está usando

In [19]:
print(m3d.dtype)
m3df=np.array(m2, dtype='float64')
print(m3df.dtype)
print(m3df)
# convierte una variable en ya definia como np.array y se define desde la librería con np.float64 por su eficiencia en la manipulación de datos
m3dff=m3d.astype(np.float64)
print(m3dff.dtype)
## PROBAR PASAR A BOOLEANO LA SERIE (0,2,0,1,1,1,0,2,3,0)
ser=(0,2,0,1,1,1,0,2,3,0)
sernp=np.array(ser, np.bool_)
print("bool", sernp)
ser=sernp.astype(np.int8)
print("int8",ser)

int64
float64
[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]]

 [[ 3.  6.  9.]
  [12. 15. 18.]
  [21. 24. 27.]]

 [[ 4.  8. 12.]
  [16. 20. 24.]
  [28. 32. 36.]]]
float64
bool [False  True False  True  True  True False  True  True False]
int8 [0 1 0 1 1 1 0 1 1 0]
