### Dimensiones
- Dimensión 0=> Escalar: un dato.
- Dimensión 1=> Vector o array; lista o serie.
- Dimensión 2=> Matriz; tabla de doble entrada.
- Dimensión n=> Tensor; conjunto de datos multidimensionales.

In [2]:
import numpy as np

* Escalar un dato aislado
* Metodo .ndim devuelve el numero de dimenciones de un array

In [5]:
escalar = np.array("Juan")
print(escalar)
escalar.ndim

Juan


0

* Vector como lista de valores

In [7]:
vector = np.array([1,2,3,4,5,6,7])
print(vector)
vector.ndim

[1 2 3 4 5 6 7]


1

* Matriz como lista de lista

In [11]:
matriz = np.array([[1,2,3,4,5,6,7],[8,7,8,8,7,6,7],[1,2,2,2,5,1,3]])
print(matriz)
matriz.ndim

[[1 2 3 4 5 6 7]
 [8 7 8 8 7 6 7]
 [1 2 2 2 5 1 3]]


2

* Tensor como lista de matrices, y a partir de esta dimensión cada array con mas de 3 dimensiones se denomina tensor

In [12]:
tensor = np.array([[[1,2,3,4,5,6,7],[8,7,8,8,7,6,7],[1,2,2,2,5,1,3]],[[1,2,3,4,5,6,7],[8,7,8,8,7,6,7],[1,2,2,2,5,1,3]],[[1,2,3,4,5,6,7],[8,7,8,8,7,6,7],[1,2,2,2,5,1,3]]])
print(tensor)
tensor.ndim

[[[1 2 3 4 5 6 7]
  [8 7 8 8 7 6 7]
  [1 2 2 2 5 1 3]]

 [[1 2 3 4 5 6 7]
  [8 7 8 8 7 6 7]
  [1 2 2 2 5 1 3]]

 [[1 2 3 4 5 6 7]
  [8 7 8 8 7 6 7]
  [1 2 2 2 5 1 3]]]


3

### Agregar dimensiones

* Cuando se crea el array con *,ndimn=x*

In [16]:
tens5 = np.array([[1,2,3,4,5,6,7],[8,7,8,8,7,6,7],[1,2,2,2,5,1,3]],ndmin=5)
print(tens5)
tens5.ndim

[[[[[1 2 3 4 5 6 7]
    [8 7 8 8 7 6 7]
    [1 2 2 2 5 1 3]]]]]


5

* Expandir dimensiones en un vector con **np.expand_dims()** determinado eje 0 para agregar fila, 1 para agregar columna

In [42]:
print(vector)
print(vector.ndim)
print("agrego fila con axis=0")
vec0 = np.expand_dims(vector, axis=0)
print(vec0)
print(vec0[0])
print(vec0[0][0])
print(vec0.ndim)
print("agrego columna con axis=1")
vec1 = np.expand_dims(vector, axis=1)
print(vec1)
print(vec1[2])
print(vec1[2][0])
print(vec1.ndim)

[1 2 3 4 5 6 7]
1
agrego fila con axis=0
[[1 2 3 4 5 6 7]]
[1 2 3 4 5 6 7]
1
2
agrego columna con axis=1
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[3]
3
2


* Quitar dimensiones vacías **np.sqeeze()**

In [44]:
print(tens5, tens5.ndim)
tens0=np.squeeze(tens5)
print(tens0, tens0.ndim)

[[[[[1 2 3 4 5 6 7]
    [8 7 8 8 7 6 7]
    [1 2 2 2 5 1 3]]]]] 5
[[1 2 3 4 5 6 7]
 [8 7 8 8 7 6 7]
 [1 2 2 2 5 1 3]] 2


### CREAR Array desde NumPy

Con Pyton, lista hecha con rango (range)

In [55]:
list(range(0,30,3))


[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

Rango generado en un array con *NumPy*

In [54]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

### ZEROS
Array de ceros

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Matriz de ceros

In [66]:
# segunda dimensión 2 filas 5 columnas
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ONES
Varias dimensiones de unos (tambien, claro se puede hacer de ceros)

In [73]:
# 4 dimensiones 2 x 3 x 4 x 5
np.ones((((2,3,4,5))))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

Serie de N numeros en un rango desde un inicio I hasta un fin F, *np.linspace(I,F,N)*

In [75]:
np.linspace(0,90,30)

array([ 0.        ,  3.10344828,  6.20689655,  9.31034483, 12.4137931 ,
       15.51724138, 18.62068966, 21.72413793, 24.82758621, 27.93103448,
       31.03448276, 34.13793103, 37.24137931, 40.34482759, 43.44827586,
       46.55172414, 49.65517241, 52.75862069, 55.86206897, 58.96551724,
       62.06896552, 65.17241379, 68.27586207, 71.37931034, 74.48275862,
       77.5862069 , 80.68965517, 83.79310345, 86.89655172, 90.        ])

Diagonal N x N *np.eye(N)*

In [76]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### RAND
Aleatoreos *np.random.rand()* cantidad N de numeros aleatorios en unarray *np.random.rand(N)*, por lo tanto para una matriz de N x M *np.random.rand(N,M)*

In [85]:
print("Escalar")
print(np.random.rand())
print("Array")
print(np.random.rand(4))
print("Matriz")
print(np.random.rand(3,4))
print ("Tensor")
print(np.random.rand(2,3,4))

Escalar
0.3369929164336821
Array
[0.90780632 0.48240453 0.72377591 0.54540246]
Matriz
[[0.15916701 0.77114359 0.80321677 0.86505962]
 [0.95400529 0.54394484 0.45980915 0.66339874]
 [0.23934975 0.22670494 0.33921944 0.17312405]]
Tensor
[[[0.60338604 0.62542923 0.21943967 0.14121809]
  [0.27055767 0.35552943 0.92426877 0.48185539]
  [0.68249222 0.895393   0.21711284 0.64036286]]

 [[0.55894316 0.38377953 0.42669412 0.70096672]
  [0.64330164 0.87387639 0.75505117 0.36722024]
  [0.55594821 0.98947707 0.06491592 0.08378238]]]


### RANDINT
También existe *randint(n,m)* para generar un entero aleatorio entre un rango n y m.

In [123]:
print("Desde 0 hasta un numero - positivos")
print(np.random.randint(15))
print("Desde N hasta M")
print(np.random.randint(-12,12))

Desde 0 hasta un numero - positivos
10
Desde N hasta M
-9


Armar array con numeros enteros aleatorios de n a m, en una matriz de p filas por q columnas *np.random.randint(n,m,(p,q))*

In [126]:
print(np.random.randint(3,99,(2,3,6)))

[[[12 96  6  7 61 72]
  [34 32 69 13 40 78]
  [83 88  6 27 72 83]]

 [[55 21 37 96 35 52]
  [37 90 94 66 58 41]
  [11 18 68 48 10  7]]]


#### CHOICE
Selecciona aleatoreamente un elemento de una lista *arr* las veces *n* (solo selecciona 1 si no se coloca coma): np.random.choice(arr,n)

In [15]:
lista_nombres = (["Marcos","Pablo","Andrea","Julieta","Analía","Ramiro", "Estefanía"])
np.random.choice(lista_nombres,3)

array(['Ramiro', 'Ramiro', 'Estefanía'], dtype='<U9')

### ROUNT
Para redondear *n* decimales los valores de una serie *arr* de decimales se utiliza np.rount(arr,n)

In [29]:
decimales= np.linspace(0,70,4)
print("Sin redondear")
print(decimales)
print("Redondeado")
print(np.round(decimales,3))


Sin redondear
[ 0.         23.33333333 46.66666667 70.        ]
Redondeado
[ 0.    23.333 46.667 70.   ]


## Shape y Reshape
Devuelve las dimensiones y la cantidad de datos en cada dimensión

In [125]:
arr=np.random.randint(1,30,(3,2,6))
print(arr)
print(arr.shape)

[[[ 6  8 15 12  8 21]
  [24  6 17 24 26  3]]

 [[ 6 13  1  5 14 28]
  [24 12  9  7  2 25]]

 [[ 4  6 22 22 16 19]
  [14 20 16 21 10 19]]]
(3, 2, 6)


Reshape cambia la estructura del arreglo, tener cuidado de no dejar datos afuera ni generar espacios vacíos

In [127]:
rarr=arr.reshape(2,6,3)
print(rarr)
print("Con np")
connp=np.reshape(arr,(3,2,6))
print(connp)

[[[ 6  8 15]
  [12  8 21]
  [24  6 17]
  [24 26  3]
  [ 6 13  1]
  [ 5 14 28]]

 [[24 12  9]
  [ 7  2 25]
  [ 4  6 22]
  [22 16 19]
  [14 20 16]
  [21 10 19]]]
Con np
[[[ 6  8 15 12  8 21]
  [24  6 17 24 26  3]]

 [[ 6 13  1  5 14 28]
  [24 12  9  7  2 25]]

 [[ 4  6 22 22 16 19]
  [14 20 16 21 10 19]]]
