## Funciones Principales

Generamos un vector de 30 valores del 3 al 30, y lo transformamos en una matriz de 5 x 6

In [2]:
import numpy as np
vec=np.random.randint(3,30,30)
matriz=vec.reshape(5,6)
matriz

array([[27, 29, 19, 14, 12, 20],
       [17, 25,  4, 19, 21, 11],
       [28, 12, 20, 11, 29, 19],
       [25,  9, 29, 26,  8,  7],
       [16, 18, 15, 18, 18,  8]])

**Buscar max / min**: maximo valor de la matriz *max()* y *min()*
* sin argumentos entre parentesis, toma toda la matriz
* con "1" en parentesis, busca los maximos de cada fila y devuelve una lista de maximos por fila
* con "0" busca los maximos de cada columna y devuelve una lista de maximos por columna
* para obtener el maximo de una fila n se coloca entre corchetes la fila[n]
* para obtener el maximo de una columna se define la columna n como vector [:,n:n+1]

In [3]:
print("Maximo valor de la matriz")
print(matriz.max())
print("Máximos de cada columna")
print(matriz.max(0))
print("Máximos de cada fila")
print(matriz.max(1))
print("Mínimo de la fila 5")
print(matriz[4].min())
print("Mínimo de la columna 2")
print(matriz[:,2:3].min())

Maximo valor de la matriz
29
Máximos de cada columna
[28 27 27 27 24 29]
Máximos de cada fila
[27 28 24 29 27]
Mínimo de la fila 5
5
Mínimo de la columna 2
3


**Buscar indice de los max / min** *argmax()* *argmin()*

Al igual que max o min, se utiliza argmax o argmin respectivamente

In [4]:
print(matriz)
print("Ubicación del minimo de la matriz")
print(matriz.argmin())
print("Ubicación de maximos por columnas")
print(matriz.argmax(0))
print("Ubicación de mínimos por filas")
print(matriz.argmin(1))
print("Ubicación del máximo de la segunda fila")
print(matriz[1].argmax())
print("Ubicación del mínimo de la tercer columna")
print(matriz[:,2:3].argmin())

[[ 8 27 18 10 22 11]
 [28  9  3  9 10 19]
 [ 4  3 14 20 24 15]
 [18  3  3 21  6 29]
 [23  5 27 27 16 16]]
Ubicación del minimo de la matriz
8
Ubicación de maximos por columnas
[1 0 4 4 2 3]
Ubicación de mínimos por filas
[0 2 1 1 1]
Ubicación del máximo de la segunda fila
0
Ubicación del mínimo de la tercer columna
1


El indice del primer máximo

In [3]:
lls=np.array([1,2,3,4,5,6,5,4,5,6])
np.argmax(lls)

5

**Amplitud** es la diferencia entre el maximo y el minimo la funcion es *ptp* (pic to pic)<br>
De la misma manera que en para los casos de *max()* y *min()* se utiliza *.ptp()*

In [6]:
print(matriz)
print("Amplitud de toda la matriz")
print(matriz.ptp())
print("Amplitud por columnas")
print(matriz.ptp(0))
print("amplitud por filas")
print(matriz.ptp(1))

[[ 8 27 18 10 22 11]
 [28  9  3  9 10 19]
 [ 4  3 14 20 24 15]
 [18  3  3 21  6 29]
 [23  5 27 27 16 16]]
Amplitud de toda la matriz
26
Amplitud por columnas
[24 24 24 18 18 18]
amplitud por filas
[19 25 21 26 22]


**Percentil**(mediana) Devuelve valores en un determinado porcentage del total de valores
* Percentil *P* del array *arr* : np.percentile(*arr*,*P*)

**Mediana** es el percentil 50
* np.median(*arr*)

**Media** Promedio de la matriz
*np.mean(*arr*)

In [26]:
print(np.percentile(matriz,25))
print(np.median(matriz))
print(np.mean(matriz))



8.25
15.5
14.933333333333334


**Sort** ordena valores, sin modificador, ordena por fila, con ",0" ordena por columna.
* np.sort(*matriz*)

**Desvío Estandar** Calcula el desvío estandar de la matriz, 0 por columnas y 1 por filas.
* np.std(*matriz*)

**Varianza** Calculo de varianza (cuadrado del devío estandar) modificado por 0 y 1.
* np.var(*matriz)

In [23]:
print(matriz)
print("Sort")
print(np.sort(matriz))
print(np.sort(matriz,0))
print(np.sort(matriz,1))
print("Std")
print(np.std(matriz))
print(np.std(matriz,0))
print(np.std(matriz,1))
print("var")
print(np.var(matriz))
print(np.var(matriz,0))
print(np.var(matriz,1))

[[ 8 27 18 10 22 11]
 [28  9  3  9 10 19]
 [ 4  3 14 20 24 15]
 [18  3  3 21  6 29]
 [23  5 27 27 16 16]]
Sort
[[ 8 10 11 18 22 27]
 [ 3  9  9 10 19 28]
 [ 3  4 14 15 20 24]
 [ 3  3  6 18 21 29]
 [ 5 16 16 23 27 27]]
[[ 4  3  3  9  6 11]
 [ 8  3  3 10 10 15]
 [18  5 14 20 16 16]
 [23  9 18 21 22 19]
 [28 27 27 27 24 29]]
[[ 8 10 11 18 22 27]
 [ 3  9  9 10 19 28]
 [ 3  4 14 15 20 24]
 [ 3  3  6 18 21 29]
 [ 5 16 16 23 27 27]]
Std
8.473225805769346
[8.9977775  9.06862724 9.18694726 6.88767014 6.85857128 6.06630036]
[6.90410506 8.18535277 7.69559759 9.94428926 7.72442015]
var
71.79555555555557
[80.96 82.24 84.4  47.44 47.04 36.8 ]
[47.66666667 67.         59.22222222 98.88888889 59.66666667]


### Concatenar
Para agregar valores al array vectores se utiliza, np.concatenate((arr1,arr2))

Para arreglos de mas de una dimension se utiliza

In [63]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([5,6])
print(arr1.ndim)
print(arr1)
print(arr2.ndim)
print(arr2)
print(np.concatenate((arr1,arr2), axis=0))

2
[[1 2]
 [3 4]]
1
[5 6]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Para concatenar, ambos arreglos deben contenr las mismas dimensiones con np.expand_dims

In [64]:
arr2=np.expand_dims(arr2,axis=0)
arr2
print(np.concatenate((arr1,arr2), axis=0))

[[1 2]
 [3 4]
 [5 6]]


Para agregar por columna de depe colocar la transpuesta. También se puede utilizar np.reshape()

In [66]:
print(np.concatenate((arr1,arr2.T),axis=1))

[[1 2 5]
 [3 4 6]]


https://numpy.org/doc/stable/reference/routines.statistics.html
Manual oficial de las funciones estadísticas

### Split
Divide array *arr* en *N* arrays np.array_split(arr, N)

In [8]:
print(lls)
print(np.array_split(lls,3))

[1 2 3 4 5 6 5 4 5 6]
[array([1, 2, 3, 4]), array([5, 6, 5]), array([4, 5, 6])]


### Where
Nos devuelve los índices de los valores que cumplen con una condición

In [29]:
lls=np.array([1,2,3,4,5,6,5,4,5,6])
print(lls)
mas4 = np.where(lls>4)
print(mas4)
mas=(["mayor","mayor","mayor","mayor","mayor","mayor","mayor","mayor","mayor","mayor"])
menos=(["menor","menor","menor","menor","menor","menor","menor","menor","menor","menor"])
condicion=lls>4
lista=np.where(condicion,mas,menos)
lls=np.expand_dims(lls,axis=0)
lista=np.expand_dims(lista,axis=0)
nuevalista=np.concatenate((lls,lista),axis=0)
print(nuevalista.T)


[1 2 3 4 5 6 5 4 5 6]
(array([4, 5, 6, 8, 9]),)
[['1' 'menor']
 ['2' 'menor']
 ['3' 'menor']
 ['4' 'menor']
 ['5' 'mayor']
 ['6' 'mayor']
 ['5' 'mayor']
 ['4' 'menor']
 ['5' 'mayor']
 ['6' 'mayor']]
